# Generated by Django 6.1 on 2026-09-09 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('creative', 'Creative'), ('physical', 'Physical'), ('relaxing', 'Relaxing')], default='physical', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
