# Generated by Django 6.1 on 2026-09-13 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('music', 'Music'), ('art and culture', 'Art and Culture'), ('sport', 'Sport'), ('movies and cinema', 'Movies and Cinema')], default='technology', max_length=20)),
                ('thumbnail', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
